### ISSUE TITLE
Copy files from repository to ./themes/BootstrapTheme

### ISSUE THREAD

**Issue by Den-Uchiwa** [Sylius/BootstrapTheme#12]
Hello, i try to use bootstrap in sylius app but when i want to add carroussel in my sylius app but its dont work.

when i write : yarn encore dev --watch
i have this error : 

/home/ecomm/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

Error: Cannot find module './themes/BootstrapTheme/webpack.config'
Require stack:
- /home/ecomm/webpack.config.js
- /home/ecomm/node_modules/webpack-cli/bin/utils/convert-argv.js
- /home/ecomm/node_modules/webpack-cli/bin/cli.js
- /home/ecomm/node_modules/webpack/bin/webpack.js
- /home/ecomm/node_modules/@symfony/webpack-encore/bin/encore.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (/home/ecomm/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/ecomm/webpack.config.js:2:24)
    at Module._compile (/home/ecomm/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (/home/ecomm/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/home/ecomm/node_modules/webpack-cli/bin/utils/convert-argv.js:116:13)
    at requireConfig (/home/ecomm/node_modules/webpack-cli/bin/utils/convert-argv.js:118:6)
    at /home/ecomm/node_modules/webpack-cli/bin/utils/convert-argv.js:125:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/ecomm/node_modules/webpack-cli/bin/utils/convert-argv.js:123:15)
    at /home/ecomm/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/home/ecomm/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /home/ecomm/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/ecomm/node_modules/webpack-cli/bin/cli.js:365:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/ecomm/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/ecomm/node_modules/@symfony/webpack-encore/bin/encore.js:63:12)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ecomm/webpack.config.js',
    '/home/ecomm/node_modules/webpack-cli/bin/utils/convert-argv.js',
    '/home/ecomm/node_modules/webpack-cli/bin/cli.js',
    '/home/ecomm/node_modules/webpack/bin/webpack.js',
    '/home/ecomm/node_modules/@symfony/webpack-encore/bin/encore.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

i think its because i dont Copy files from repository to ./themes/BootstrapTheme because dont know where i can find this repository and where copy

**Comment by kulczy** [comment]
Hi @Den-Uchiwa all files are [here](https://github.com/Sylius/BootstrapTheme). Then follow [these](https://github.com/Sylius/BootstrapTheme) instructions. And for the future, if you need help, try our [slack](https://sylius.com/slack)
